/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms2;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author skdie
 */
public class mainwd extends javax.swing.JFrame {
    /**
     * Creates new form mainwd
     */
    public mainwd() {
        initComponents();
       // setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Menu");
        micon.setOpaque(false);
        micon.setContentAreaFilled(false);
        micon.setBorderPainted(false);
        aicon.setOpaque(false);
        aicon.setContentAreaFilled(false);
        aicon.setBorderPainted(false);
        uicon.setOpaque(false);
        uicon.setContentAreaFilled(false);
        uicon.setBorderPainted(false);
        
        eicon.setOpaque(false);
        eicon.setContentAreaFilled(false);
        eicon.setBorderPainted(false);
        lcicon.setOpaque(false);
        lcicon.setContentAreaFilled(false);
        lcicon.setBorderPainted(false);
        showlicon.setOpaque(false);
        showlicon.setContentAreaFilled(false);
        showlicon.setBorderPainted(false);
        slicon.setOpaque(false);
        slicon.setContentAreaFilled(false);
        slicon.setBorderPainted(false);
        ulicon.setOpaque(false);
        ulicon.setContentAreaFilled(false);
        ulicon.setBorderPainted(false);
        dlicon.setOpaque(false);
        dlicon.setContentAreaFilled(false);
        dlicon.setBorderPainted(false);
        setting.setOpaque(false);
        setting.setContentAreaFilled(false);
        setting.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        micon = new javax.swing.JButton();
        aicon = new javax.swing.JButton();
        uicon = new javax.swing.JButton();
        eicon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lcicon = new javax.swing.JButton();
        slicon = new javax.swing.JButton();
        showlicon = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        ulicon = new javax.swing.JButton();
        dlicon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        micon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon123.png"))); // NOI18N
        micon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                miconFocusGained(evt);
            }
        });
        micon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miconMouseEntered(evt);
            }
        });
        micon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miconActionPerformed(evt);
            }
        });
        jPanel1.add(micon, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 100, 47, 40));

        aicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon212.png"))); // NOI18N
        aicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aiconMouseEntered(evt);
            }
        });
        aicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiconActionPerformed(evt);
            }
        });
        jPanel1.add(aicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 50, 40));

        uicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon3.png"))); // NOI18N
        uicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uiconMouseEntered(evt);
            }
        });
        uicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiconActionPerformed(evt);
            }
        });
        jPanel1.add(uicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 50, 40));

        eicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon5.png"))); // NOI18N
        eicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eiconMouseEntered(evt);
            }
        });
        eicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eiconActionPerformed(evt);
            }
        });
        jPanel1.add(eicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 540));

        jPanel2.setBackground(new java.awt.Color(218, 232, 202));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 43, -1));

        search.setBackground(new java.awt.Color(218, 232, 202));
        search.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        search.setText("Search Student Full Name");
        search.setBorder(null);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 28, 230, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/search_icon.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 820, 60));

        jPanel3.setBackground(new java.awt.Color(184, 208, 220));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lcicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/create_icon.png"))); // NOI18N
        lcicon.setText("jButton1");
        lcicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lciconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lciconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lciconMouseEntered(evt);
            }
        });
        lcicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lciconActionPerformed(evt);
            }
        });
        jPanel3.add(lcicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 25, 90, 85));

        slicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/searchlarge.png"))); // NOI18N
        slicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sliconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sliconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sliconMouseEntered(evt);
            }
        });
        slicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliconActionPerformed(evt);
            }
        });
        jPanel3.add(slicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 25, 85, 85));

        showlicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/showall.png"))); // NOI18N
        showlicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showliconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showliconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showliconMouseEntered(evt);
            }
        });
        showlicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showliconActionPerformed(evt);
            }
        });
        jPanel3.add(showlicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 25, 86, 85));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/Setting.png"))); // NOI18N
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
        });
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        jPanel3.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 158, 85, 85));

        ulicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/updatelarge.png"))); // NOI18N
        ulicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uliconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uliconMouseEntered(evt);
            }
        });
        ulicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uliconActionPerformed(evt);
            }
        });
        jPanel3.add(ulicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 158, 90, 85));

        dlicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/support1.png"))); // NOI18N
        dlicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dliconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dliconMouseExited(evt);
            }
        });
        dlicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dliconActionPerformed(evt);
            }
        });
        jPanel3.add(dlicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 158, 80, 85));

        jLabel3.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 94, 27));

        jLabel5.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("See All");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 110, 90, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 110, 85, 20));

        jLabel7.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Setting");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 247, 80, -1));

        jLabel8.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Update Software");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 247, 150, -1));

        jLabel9.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Support");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 247, 70, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 820, 290));

        jPanel4.setBackground(new java.awt.Color(242, 240, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Raleway Light", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("SMS");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 90));

        jLabel2.setFont(new java.awt.Font("Raleway Light", 0, 36)); // NOI18N
        jLabel2.setText("School Management System");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 490, 40));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 370, 180));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 820, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
        if(search.getText().equals("Search Student Full Name"))
        search.setText("");
    }//GEN-LAST:event_searchMousePressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String a ="name";
        String b=search.getText();
         System.out.println(b);
        
        try{
           
                Connection con;
                PreparedStatement ps;
                ResultSet rs;
                Statement stmt;
                String path=("jdbc:mysql://localhost:3306/student");
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection(path,"root","");
                stmt=con.createStatement();
                stmt.executeUpdate("INSERT INTO `search` (`prefer`, `item`) VALUES ('"+a+"', '"+b+"')");
                JOptionPane.showMessageDialog(null,"executed from main");
                searchshow aaa=new searchshow();
                aaa.setVisible(true);
                dispose();
                                 
            }
        catch(Exception E)
        {
            JOptionPane.showMessageDialog(null,"Error" +E);

        }
        searchshow aa=new searchshow();
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void miconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miconActionPerformed

    private void aiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiconActionPerformed
        // TODO add your handling code here:
        NewJFrame aa=new NewJFrame();
        aa.setVisible(true);
        dispose();
    }//GEN-LAST:event_aiconActionPerformed

    private void miconFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miconFocusGained
        // TODO add your handling code here:
      //   micon.setBackground(Color.GRAY);
    }//GEN-LAST:event_miconFocusGained

    private void miconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miconMouseEntered
        // TODO add your handling code here:
       //  micon.setBackground(Color.GRAY);
           try {
            Image img = ImageIO.read(getClass().getResource("icon10.png"));
            micon.setIcon(new ImageIcon(img));

                 } 
           catch (IOException ex)
           {
            System.out.println(ex);
          }
           
           
           
    }//GEN-LAST:event_miconMouseEntered

    private void miconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon123.png"));
            micon.setIcon(new ImageIcon(img));
            img = ImageIO.read(getClass().getResource("create_icon.png"));
            lcicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_miconMouseExited

    private void uiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiconMouseEntered
        // TODO add your handling code here:
          // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon9.png"));
            uicon.setIcon(new ImageIcon(img));
            img = ImageIO.read(getClass().getResource("l4.png"));
            ulicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_uiconMouseEntered

    private void uiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiconMouseExited
        // TODO add your handling code here:
          // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon3.png"));
            uicon.setIcon(new ImageIcon(img));
            img = ImageIO.read(getClass().getResource("updatelarge.png"));
            ulicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_uiconMouseExited

    private void aiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aiconMouseEntered
        // TODO add your handling code here:
          try {
            Image img = ImageIO.read(getClass().getResource("icon13.png"));
            aicon.setIcon(new ImageIcon(img));
             img = ImageIO.read(getClass().getResource("l1.png"));
            lcicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_aiconMouseEntered

    private void aiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aiconMouseExited
        // TODO add your handling code here:
          try {
            Image img = ImageIO.read(getClass().getResource("icon212.png"));
            aicon.setIcon(new ImageIcon(img));
            img = ImageIO.read(getClass().getResource("create_icon.png"));
            lcicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_aiconMouseExited

    private void showliconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showliconActionPerformed
        // TODO add your handling code here:
         try {
            Image img = ImageIO.read(getClass().getResource("l21.png"));
            showlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
         showprofession aa=new showprofession();
         aa.setVisible(true);
         dispose();
    }//GEN-LAST:event_showliconActionPerformed

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
        //search.setText("Search");
        if(search.getText().equals(""))
            search.setText("Search Student Full Name");
    }//GEN-LAST:event_searchMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered

        // TODO add your handling code here:
       
    }//GEN-LAST:event_searchMouseEntered

    private void lciconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lciconMouseEntered
        // TODO add your handling code here:
        
        try {
            Image img = ImageIO.read(getClass().getResource("l1.png"));
            lcicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_lciconMouseEntered

    private void lciconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lciconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("create_icon.png"));
            lcicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_lciconMouseExited

    private void showliconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showliconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l2.png"));
            showlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_showliconMouseEntered

    private void showliconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showliconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("showall.png"));
            showlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_showliconMouseExited

    private void sliconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("searchlarge.png"));
            slicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_sliconMouseExited

    private void sliconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l3.png"));
            slicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_sliconMouseEntered

    private void uliconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uliconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l4.png"));
            ulicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_uliconMouseEntered

    private void uliconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uliconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("updatelarge.png"));
            ulicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_uliconMouseExited

    private void dliconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dliconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("support.png"));
            dlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_dliconMouseEntered

    private void dliconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dliconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("support1.png"));
            dlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_dliconMouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l6.png"));
            setting.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
        
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited

        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("Setting.png"));
            setting.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_settingMouseExited

    private void lciconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lciconMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lciconMouseClicked

    private void showliconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showliconMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_showliconMouseClicked

    private void sliconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sliconMouseClicked

    private void lciconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lciconActionPerformed
        // TODO add your handling code here:
        
        try {
            Image img = ImageIO.read(getClass().getResource("l11.png"));
            lcicon.setIcon(new ImageIcon(img));
            
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }        
           selectProfession aas=new selectProfession();
             dispose();
           aas.setVisible(true);
         
         
    }//GEN-LAST:event_lciconActionPerformed

    private void sliconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliconActionPerformed

        // TODO add your handling code here:
         try {
            Image img = ImageIO.read(getClass().getResource("l31.png"));
            slicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
          searchMain aa=new searchMain();
          aa.setVisible(true);
          dispose();
    }//GEN-LAST:event_sliconActionPerformed

    private void uliconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uliconActionPerformed
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l41.png"));
            ulicon.setIcon(new ImageIcon(img));
            update aa=new update();
            aa.setVisible(true);
            dispose();
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_uliconActionPerformed

    private void dliconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dliconActionPerformed
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("support1.png"));
            dlicon.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
    }//GEN-LAST:event_dliconActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("l61.png"));
            setting.setIcon(new ImageIcon(img));
                 } 
           catch (Exception ex)
           {
            System.out.println(ex);
          }
        settingwd aaaa=new settingwd();
        aaaa.setVisible(true);
        dispose();
    }//GEN-LAST:event_settingActionPerformed

    private void uiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiconActionPerformed

            update aa=new update();
            aa.setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_uiconActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
         if(search.getText().equals("Search Student Full Name"))
        search.setText("");
    }//GEN-LAST:event_searchKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
       // String a=getKeyReleased();
    }//GEN-LAST:event_formKeyReleased

    private void eiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon5.png"));
            eicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_eiconMouseExited

    private void eiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon7.png"));
            eicon.setIcon(new ImageIcon(img));
        }
        catch (IOException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_eiconMouseEntered

    private void eiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eiconActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_eiconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aicon;
    private javax.swing.JButton dlicon;
    private javax.swing.JButton eicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lcicon;
    private javax.swing.JButton micon;
    private javax.swing.JTextField search;
    private javax.swing.JButton setting;
    private javax.swing.JButton showlicon;
    private javax.swing.JButton slicon;
    private javax.swing.JButton uicon;
    private javax.swing.JButton ulicon;
    // End of variables declaration//GEN-END:variables
}
