/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms2;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;   
import javax.swing.JFileChooser;


/**
 *
 * @author skdie
 */
public class NewJFrame extends javax.swing.JFrame {
    int i;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Create/Add Student");

         micon.setOpaque(false);
        micon.setContentAreaFilled(false);
        micon.setBorderPainted(false);
        aicon.setOpaque(false);
        aicon.setContentAreaFilled(false);
        aicon.setBorderPainted(false);
        uicon.setOpaque(false);
        uicon.setContentAreaFilled(false);
        uicon.setBorderPainted(false);
      
        eicon.setOpaque(false);
        eicon.setContentAreaFilled(false);
        eicon.setBorderPainted(false);
        
         
            setValue();    
              try
        {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Statement stmt;
            String path=("jdbc:mysql://localhost:3306/student");
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(path,"root","");
            stmt=con.createStatement();
            ps=con.prepareStatement("Select * from `data` ");
            rs=ps.executeQuery();
            
            int i = 1;
           while(rs.next())
         {
                i=i+1;
                
                
            } 
           id.setText(Integer.toString(i));
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e );
            
            System.out.println("error "+e);
        } 
        
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        micon = new javax.swing.JButton();
        aicon = new javax.swing.JButton();
        uicon = new javax.swing.JButton();
        eicon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        religion = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        y = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        micon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon123.png"))); // NOI18N
        micon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                miconFocusGained(evt);
            }
        });
        micon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miconMouseEntered(evt);
            }
        });
        micon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miconActionPerformed(evt);
            }
        });
        jPanel1.add(micon, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 100, 47, 40));

        aicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon212.png"))); // NOI18N
        aicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aiconMouseEntered(evt);
            }
        });
        aicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiconActionPerformed(evt);
            }
        });
        jPanel1.add(aicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 50, 40));

        uicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon3.png"))); // NOI18N
        uicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uiconMouseEntered(evt);
            }
        });
        jPanel1.add(uicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 50, 40));

        eicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/icon5.png"))); // NOI18N
        eicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eiconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eiconMouseEntered(evt);
            }
        });
        eicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eiconActionPerformed(evt);
            }
        });
        jPanel1.add(eicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 540));

        jPanel3.setBackground(new java.awt.Color(242, 240, 230));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 40));

        jLabel2.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel2.setText("Create/Add a student");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 40));

        jLabel3.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Father's Phone No.");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Name ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));

        jLabel5.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Class");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));

        jLabel6.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Gender");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jLabel7.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Address");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, -1));

        jLabel8.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Mother's name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, -1));

        jLabel9.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Father's name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, -1));

        jLabel10.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Roll no");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        jLabel11.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Section");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 90, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 10, 310));

        jLabel12.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("DOB");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 90, -1));

        jLabel13.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Religion");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 90, -1));

        fno.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        fno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnoActionPerformed(evt);
            }
        });
        jPanel3.add(fno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 170, -1));

        jLabel14.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel14.setText(":");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 20, -1));

        jLabel16.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 20, -1));

        jLabel17.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel17.setText(":");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 20, -1));

        jLabel18.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel18.setText(":");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 20, -1));

        jLabel19.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel19.setText(":");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 20, -1));

        jLabel20.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 20, -1));

        jLabel21.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel21.setText(":");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 20, -1));

        jLabel24.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel24.setText(":");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 20, -1));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(242, 240, 230));
        id.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 0, 0));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        clas.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        clas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clasKeyReleased(evt);
            }
        });
        jPanel3.add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, -1));

        address.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, -1));

        mname.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        jPanel3.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 170, -1));

        fname.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, -1));

        sec.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        jPanel3.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 170, -1));

        religion.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        jPanel3.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 170, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 40));

        gender.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female", "other" }));
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 30));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 100, 40));

        jLabel26.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel26.setText("Registration no.");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        y.setFont(new java.awt.Font("Raleway Light", 0, 15)); // NOI18N
        y.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        jPanel3.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 60, 25));

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 40, -1));

        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        jPanel3.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 40, -1));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel23.setText("DD");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, 20));

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel25.setText("YYYY");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, 20));

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel27.setText("MM");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, 20));
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel32.setForeground(new java.awt.Color(241, 26, 26));
        jLabel32.setText("*");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 30, -1));

        jLabel33.setForeground(new java.awt.Color(241, 26, 26));
        jLabel33.setText("*");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 30, -1));

        jLabel34.setForeground(new java.awt.Color(241, 26, 26));
        jLabel34.setText("*");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 30, -1));

        jLabel35.setForeground(new java.awt.Color(241, 26, 26));
        jLabel35.setText("*");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 30, -1));

        jLabel36.setForeground(new java.awt.Color(241, 26, 26));
        jLabel36.setText("*");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 30, -1));

        jLabel38.setForeground(new java.awt.Color(241, 26, 26));
        jLabel38.setText("*");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 30, -1));

        jLabel39.setForeground(new java.awt.Color(241, 26, 26));
        jLabel39.setText("*");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 30, -1));

        jLabel40.setForeground(new java.awt.Color(241, 26, 26));
        jLabel40.setText("*");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 30, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, -1));

        roll.setEditable(false);
        roll.setBackground(new java.awt.Color(242, 240, 230));
        roll.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        roll.setForeground(new java.awt.Color(255, 0, 0));
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        jPanel3.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 170, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 820, 480));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 30));

        jPanel2.setBackground(new java.awt.Color(218, 232, 202));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 43, -1));

        search.setBackground(new java.awt.Color(218, 232, 202));
        search.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        search.setText("Search Student Full Name");
        search.setBorder(null);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 28, 230, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms2/search_icon.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 820, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miconFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miconFocusGained
        // TODO add your handling code here:
        //   micon.setBackground(Color.GRAY);
    }//GEN-LAST:event_miconFocusGained
    private void setValue(){
        try{
        Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Statement stmt;
            String path=("jdbc:mysql://localhost:3306/student");
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(path,"root","");
            stmt=con.createStatement();
            ps=con.prepareStatement("Select * from `data`");
            rs=ps.executeQuery();
            
           i = 1;
           while(rs.next())
         {
                i=i+1;
                
                
            } 
           id.setText(Integer.toString(i));
              
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e );
            
            System.out.println("error "+e);
        }

    }
    private void miconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miconMouseEntered
        // TODO add your handling code here:
        //  micon.setBackground(Color.GRAY);
        try {
            Image img = ImageIO.read(getClass().getResource("icon10.png"));
            micon.setIcon(new ImageIcon(img));
        }
        catch (IOException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_miconMouseEntered

    private void miconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon123.png"));
            micon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_miconMouseExited

    private void miconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miconActionPerformed
        // TODO add your handling code here:
        mainwd aa=new mainwd();
        aa.setVisible(true);
        dispose();
    }//GEN-LAST:event_miconActionPerformed

    private void aiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aiconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon13.png"));
            aicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_aiconMouseEntered

    private void aiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aiconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon212.png"));
            aicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_aiconMouseExited

    private void aiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiconActionPerformed

    private void uiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiconMouseEntered
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon9.png"));
            uicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_uiconMouseEntered

    private void uiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiconMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon3.png"));
            uicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_uiconMouseExited

    private void eiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiconMouseEntered
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon7.png"));
            eicon.setIcon(new ImageIcon(img));
        }
        catch (IOException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_eiconMouseEntered

    private void eiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiconMouseExited
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("icon5.png"));
            eicon.setIcon(new ImageIcon(img));
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_eiconMouseExited

    private void eiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eiconActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_eiconActionPerformed

    private void fnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnoActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here
            
            if((id.getText().equals("")))
                    JOptionPane.showMessageDialog(null,"Enter Full User Name");
            else if((clas.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Class cannot be left empty");
            else if((address.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Address cannot be left empty");
            else if((mname.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Mother name cannot be left empty");
            else if((fname.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Father name cannot be left empty");
            else if((sec.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Section cannot be left empty");
            else if((y.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Year cannot be left empty");
            else if((m.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Month cannot be left empty");
            else if((d.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Day cannot be left empty");
          //  else if((religion.getText()).equals(""))
           //         JOptionPane.showMessageDialog(null,"Religion cannot be left empty");
            else if((fno.getText()).equals(""))
                    JOptionPane.showMessageDialog(null,"Father number cannot be left empty");
            else
            {


        
                try
               {
                    Connection con;
                   PreparedStatement ps;
                   ResultSet rs;
                   Statement stmt;
                   String path=("jdbc:mysql://localhost:3306/student");
                       Class.forName("com.mysql.jdbc.Driver");
                       con=DriverManager.getConnection(path,"root","");
                   stmt=con.createStatement();
                   String dob= y.getText()+"/"+m.getText()+"/"+d.getText();
                   stmt.executeUpdate("INSERT INTO `data` (`name`, `class`, `gender`,"
                           + " `address`, `mname`, `fname`, `roll`, `section`, "
                           + "`religion`, `fno`,`dob`,`id`) VALUES "
                           + "('"+name.getText()+"', "
                                   + "'"+clas.getText()+"', '"+gender.getSelectedItem()
                           +"', '"+address.getText()+"', '"+mname.getText()+"', '"+
                           fname.getText()+"', '"+id.getText()+"', '"+
                           sec.getText()+"', '"+religion.getText()+"', '"+
                    fno.getText()+"','"+dob+"','"+id.getText()+"')");
                    id.setText("");
                    clas.setText("");
                    address.setText("");
                    mname.setText("");
                    fname.setText("");
                    id.setText("");
                    sec.setText("");
                    religion.setText("");
                    fno.setText("");
                    y.setText("");
                    m.setText("");
                    d.setText("");
                    name.setText("");
                    JOptionPane.showMessageDialog(null,"successful");
                    id.setText(Integer.toString(1+i));
                            setValue();
                }
                catch(Exception e)
                {
                    System.out.println("error "+e);
                }  
            }
       
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainwd aa=new mainwd();
        aa.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
        if(search.getText().equals("Search Student Full Name"))
        search.setText("");
    }//GEN-LAST:event_searchMousePressed

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
        //search.setText("Search");
        if(search.getText().equals(""))
        search.setText("Search Student Full Name");
    }//GEN-LAST:event_searchMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered

        // TODO add your handling code here:

    }//GEN-LAST:event_searchMouseEntered

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String a ="name";
        String b=search.getText();
        System.out.println(b);

        try{

            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Statement stmt;
            String path=("jdbc:mysql://localhost:3306/student");
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(path,"root","");
            stmt=con.createStatement();
            stmt.executeUpdate("INSERT INTO `search` (`prefer`, `item`) VALUES ('"+a+"', '"+b+"')");
            JOptionPane.showMessageDialog(null,"executed from main");
            searchshow aaa=new searchshow();
            aaa.setVisible(true);
            dispose();

        }
        catch(Exception E)
        {
            JOptionPane.showMessageDialog(null,"Error" +E);

        }
        searchshow aa=new searchshow();

    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        if(search.getText().equals("Search Student Full Name"))
        search.setText("");
    }//GEN-LAST:event_searchKeyPressed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void clasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clasKeyReleased

         // TODO add your handling code here:
        try
        {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Statement stmt;
            String path=("jdbc:mysql://localhost:3306/student");
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(path,"root","");
            stmt=con.createStatement();
            ps=con.prepareStatement("Select * from `data` where `class` = '"+clas.getText()+"' ");
            rs=ps.executeQuery();
            
            int i = 1;
           while(rs.next())
         {
                i=i+1;
                
                
         } 
         roll.setText(Integer.toString(i));
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e );
            
            System.out.println("error "+e);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_clasKeyReleased

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton aicon;
    private javax.swing.JTextField clas;
    private javax.swing.JTextField d;
    private javax.swing.JButton eicon;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fno;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField m;
    private javax.swing.JButton micon;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField name;
    private javax.swing.JTextField religion;
    private javax.swing.JTextField roll;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sec;
    private javax.swing.JButton uicon;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
